[package]
name = "gbparser"
version = "0.1.0"
authors = ["Felipe Sciammarella <fl.sciammarella@ufrj.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "^2.1"
pest_derive = "^2.1"